#!/bin/bash
set -eo pipefail
trap '{ exit 1; }' INT

source ./conf/paths.sh
source ./conf/output.sh
source ./conf/docker.sh
source ./conf/git.sh
source ./conf/pip.sh
source ./conf/homebrew.sh
source ./conf/io.sh
source ./conf/setup-scripts

validate_docker_setup

# This isn't working currently
# docker_prepare

prepare_homebrew() {
    check_homebrew_install
    check_homebrew_package git

    # MySQL is being a pain in the ass working with Pytohn3.7, it is having trouble
    # finding the mysql_config file, which is in /usr/local/.  For now, we are just
    # going to use sqlite.db until we decide to go with PostGreSQL or MySQL.
    # check_homebrew_package mysql
    # check_homebrew_package mysql-client

    if [ ! -e /usr/local/bin/python3.7 ]; then
        check_homebrew_package python@3.7
    fi
}


echo "Setting up scripts"
install_comp_scripts

clone_sub_repositories(){
    intro "Checking for comp-community-api repo..."
    if [ -e "${COMP_ROOT}/www/api/.git/HEAD" ]; then
        success "comp-community-api repository is already cloned."
        end_step
    else
        installing "Cloning comp-community-api repository"
        git clone git@github.com:${API_REPO} "${API_ROOT}" \
            || throw_error "Could not clone comp-community-api"
        end_step
    fi
}

prepare_homebrew

pip_check_install virtualenv
check_virtualenv_install

check_gitconfig_exists

# Currently having an issue with conflicting ports
# check_listening_ports

clone_sub_repositories
install_comp_scripts

end_step
success "All comp-community prerequisites satisfied, run:"
echo ">>> . bin/activate"
echo ">>> comp setup"
